// react-todolist/src/components/TodoInput.jsx
import React, { Component } from 'react';

class TodoInput extends Component {
  state = {
    todoValue: ''
  }

  setTodoValue(e) {
    this.setState({
      todoValue: e.target.value
    })
  }

  addTodo() {
    const _val = this.state.todoValue.trim();
    const { addTodoItem }  = this.props;

    if(_val.length === 0) {
      return;
    }

    addTodoItem({
      id: new Date().getTime(),
      content: _val,
      completed: false
    })

    this.setState({
      todoValue: ''
    })
  }

  render() {
    const { todoValue } = this.state;

    return (
      <div>
        <input type="text"
          value={todoValue}
          onChange={(e) => this.setTodoValue(e)}
        />
        <button onClick={this.addTodo.bind(this)}>增加</button>
      </div>
    )
  }
}

export default TodoInput;

// vue-todolist/src/components/TodoInput.vue
<template>
  <div>
    <input 
      type="text" 
      v-model="todoValue"
      @input="setTodoValue($event)"
    />
    <button @click="addTodoItem">增加 </button>
  </div>
</template>

<script>
export default {
  name: 'TodoInput',
  data() {
    return {
      todoValue: ''
    } 
  },
  methods: {
    setTodoValue(e) {
      this.todoValue = e.target.value; 
    },
    addTodoItem() {
      const _val =  this.todoValue.trim();

      if(_val.length === 0) {
        return;
      }
      
      this.$emit('addTodoItem', {
        id: new Date().getTime(),
        content: _val,
        completed: false
      });

      this.todoValue = '';
    }
  }
}
</script>
