// vue3-todolist/src/components/TodoInput.vue
<template>
  <div>
    <input
      type="text" 
      v-model="todoValue"
      @click="setTodoValue($event )"
    />
    <button @click="addTodoItem">增加</button>
  </div>
</template>

<script>
import { ref } from 'vue';

export default {
  name: 'TodoInput',
  setup(props, ctx) {
    const todoValue = ref('');

    const setTodoValue = (e) => {
      todoValue.value = e.target.value;
    }

    const addTodoItem = () => {
      const _val = todoValue.value.trim();

      if(_val.length === 0) {
        return
      }
      ctx.emit('addTodoItem', {
        id: new Date().getTime(),
        content: _val,
        completed: false
      })
      todoValue.value = '';
    }

    return {
      todoValue,
      setTodoValue,
      addTodoItem
    }
  }
}
</script>

// react-todolist/src/components/TodoInput.jsx
import React, { Component } from 'react';

class TodoInput extends Component {
  state = {
    todoValue: ''
  }

  setTodoValue(e) {
    this.setState({
      todoValue: e.target.value
    })
  }

  addTodo() {
    const _val = this.state.todoValue.trim();
    const { addTodoItem }  = this.props;

    if(_val.length === 0) {
      return;
    }

    addTodoItem({
      id: new Date().getTime(),
      content: _val,
      completed: false
    })

    this.setState({
      todoValue: ''
    })
  }

  render() {
    const { todoValue } = this.state;

    return (
      <div>
        <input type="text"
          value={todoValue}
          onChange={(e) => this.setTodoValue(e)}
        />
        <button onClick={this.addTodo.bind(this)}>增加</button>
      </div>
    )
  }
}

export default TodoInput;
