// vue3-todolist/src/components/TodoInput.vue
<template>
  <div>
    <input
      type="text" 
      v-model="todoValue"
      @click="setTodoValue($event )"
    />
    <button @click="addTodoItem">增加</button>
  </div>
</template>

<script>
import { ref } from 'vue';

export default {
  name: 'TodoInput',
  setup(props, ctx) {
    const todoValue = ref('');

    const setTodoValue = (e) => {
      todoValue.value = e.target.value;
    }

    const addTodoItem = () => {
      const _val = todoValue.value.trim();

      if(_val.length === 0) {
        return
      }
      ctx.emit('addTodoItem', {
        id: new Date().getTime(),
        content: _val,
        completed: false
      })
      todoValue.value = '';
    }

    return {
      todoValue,
      setTodoValue,
      addTodoItem
    }
  }
}
</script>

// hooks-todolist/src/components/TodoInput.jsx
import React, { useRef } from 'react';

function TodoInput(props) {
  const inputRef = useRef();
  const { addTodoItem } = props;
  const addTodo = () => {
    const _val = inputRef.current.value.trim()

    if(_val.length === 0) {
      return;
    }

    addTodoItem({
      id: new Date().getTime(),
      content: _val,
      completed: false
    })

    inputRef.current.value = '';
  }

  return (
    <div>
      <input type="text" 
        ref={inputRef}
      />
      <button 
        onClick={addTodo}
      >
        增加
      </button>
    </div>
  )
}

export default TodoInput;
