// react-todolist/src/App.jsx
import React, { Component } from 'react';
import TodoInput from './components/TodoInput';
import TodoList from './components/TodoList';

class App extends Component {
  state = {
    todoList: []
  }

  addTodoItem(todoItem) {
    this.state.todoList.push(todoItem)
    this.setState({
      todoList: this.state.todoList
    })
  }

  setCompleted(id) {
    const todoList = this.state.todoList.map(item => {
      if(item.id === id) {
        item.completed = !item.completed;
      }

      return item;
    })
    this.setState({todoList})
  }

  removeTodoItem(id) {
    const todoList = this.state.todoList.filter(item => item.id !== id)

    this.setState({todoList})
  }

  render() {
    return (
      <div>
        <TodoInput 
          addTodoItem={this.addTodoItem.bind(this)}
        />
        <TodoList 
          todoList={this.state.todoList}
          setCompleted={this.setCompleted.bind(this)}
          removeTodoItem={this.removeTodoItem.bind(this)}
        />
      </div>
    )
  }
}

export default App;

// vue3-todolist/src/App.vue
<template>
  <div>
    <TodoInput 
      @addTodoItem="addTodoItem"
    />
    <TodoList 
      :todoList="todoList"
      @setCompleted="setCompleted"
      @removeTodoItem="removeTodoItem"
    />
  </div>
</template>

<script>
import TodoInput from '@/components/TodoInput';
import TodoList from '@/components/TodoList';
import { reactive, toRefs } from 'vue';

export default {
  name: 'App',
  components: {
    TodoInput,
    TodoList
  },
  setup(props) {
    const state = reactive({
      todoList: [] 
    })

    const addTodoItem = (todoItem) => {
      state.todoList.push(todoItem);
    }

    const setCompleted = (id) => {
      state.todoList = state.todoList.map(item => {
        if(item.id === id) {
          item.completed = !item.completed
        }

        return item;
      })
    }

    const removeTodoItem = (id) => {
      state.todoList = state.todoList.filter(item => item.id !== id)
    }

    return {
      addTodoItem,
      setCompleted,
      removeTodoItem,
      ...toRefs(state)
    }
  }
}
</script>
